export enum Prefecture {
  Hokkaido = 'hokkaido',
  Aomori = 'aomori',
  Iwate = 'iwate',
  Miyagi = 'miyagi',
  Akita = 'akita',
  Yamagata = 'yamagata',
  Hukushima = 'hukushima',
  Ibaragi = 'ibaragi',
  Tochigi = 'tochigi',
  Gunnma = 'gunnma',
  Saitama = 'saitama',
  Chiba = 'chiba',
  Tokyo = 'tokyo',
  Kanagawa = 'kanagawa',
  Niigata = 'niigata',
  Toyama = 'toyama',
  Ishikawa = 'ishikawa',
  Hukui = 'hukui',
  Yamanashi = 'yamanashi',
  Nagano = 'nagano',
  Gihu = 'gihu',
  Shizuoka = 'shizuoka',
  Aichi = 'aichi',
  Mie = 'mie',
  Shiga = 'shiga',
  Kyoto = 'kyoto',
  Osaka = 'osaka',
  Hyogo = 'hyogo',
  Nara = 'nara',
  Wakayama = 'wakayama',
  Tottori = 'tottori',
  Shimane = 'shimane',
  Okayama = 'okayama',
  Hiroshima = 'hiroshima',
  Yamaguchi = 'yamaguchi',
  Tokushima = 'tokushima',
  Kagawa = 'kagawa',
  Ehime = 'ehime',
  Kochi = 'kochi',
  Hukuoka = 'hukuoka',
  Saga = 'saga',
  Nagasaki = 'nagasaki',
  Kumamoto = 'kumamoto',
  Oita = 'oita',
  Miyazaki = 'miyazaki',
  Kagoshima = 'kagoshima',
  Okinawa = 'okinawa',
}

export interface Address {
  prefecture: Prefecture;
  municipalities: string;
  houseNumber: string;
}
