version: '2'

services: 
  vs-ipfs:
    container_name: vs-ipfs
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001" # ipfs swarm - expose if needed/wanted
      - "5001:5001" # ipfs api - expose if needed/wanted
      - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/vs-ipfs:/data/vs-ipfs
    command: config --json API.HTTPHeaders.Access-Control-Allow-Origin  '["http://localhost:3000", "http://localhost:3001"]'
    command: daemon